kind: Deployment
apiVersion: apps/v1
metadata:
  name: cve-2017-5638-git
  namespace: cve
  labels:
    app: cve-2017-5638-git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cve-2017-5638-git
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cve-2017-5638-git
        deploymentconfig: cve-2017-5638-git
    spec:
      containers:
        - name: cve-2017-5638-git
          image: mancubus/cve-2017-5638:latest
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: cve
spec:
  selector:
    app: cve-2017-5638-git
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: catmeme
  namespace: cve
spec:
  to:
    kind: Service
    name: svc
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
